# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-03 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotTranslation', '0002_auto_20190703_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_city', models.CharField(max_length=10)),
                ('user_state', models.CharField(max_length=10)),
                ('user_country', models.CharField(max_length=10)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=10)),
            ],
        ),
    ]
