# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotTranslation', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_collect_pic',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='user_collect_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_collect_url',
            field=models.CharField(default='', max_length=80),
        ),
    ]
