# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotTranslation', '0004_auto_20190704_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=10)),
                ('article_url', models.CharField(max_length=80)),
                ('article_pic', models.CharField(max_length=80)),
                ('article_briefcontent', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_collect_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_collect_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_collect_url',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotTranslation.user'),
        ),
    ]
