# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotTranslation', '0005_auto_20190704_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_hot',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='article_star',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default='0'),
        ),
    ]
